esc:
	gcc escalonador.c -o escalonador.out -Wall
	./escalonador.out

escal:
	gcc -o escalonador escalonador.c -ansi -Wall -pedantic -std=c99
	escalonador.exe

v1:
	gcc rascunho.c -o rascunho.out -Wall
	./rascunho.out
