# -*- coding: utf-8 -*-
"""Lista 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWLzHtzyHENsRndAQpghY7ngikzfi0gk
"""

install.packages('triangle')
install.packages('igraph')

"""## Tarefa 1"""

library(igraph)
library(triangle)

#1- Estruturas de dados globais
n  <- 14
Ns <- 10000

parDur <- matrix(data = c(
  0,   0.1, 0.2,
  4,   6,   10,
  2,   5,   8,
  2,   3,   6,
  0.5, 1,   2,
  3,   6,   10,
  1,   2,   4,
  0.5, 1,   3,
  2,   3,   6,
  2,   3,   5,
  1,   2,   3,
  1,   2,   4,
  3,   5,   8,
  0,   0.1, 0.2
), ncol = 3, byrow = TRUE)
# colunas: [Min, Mprov (moda), Max]

elos <- c(1,2, 1,3, 1,4, 2,9, 3,5, 3,6, 3,7,
          4,8, 5,10, 6,12, 7,11, 7,8, 8,13,
          9,14, 10,12, 11,12, 12,13, 13,14)

Suc <- list(c(2,3,4), 9, c(5,6,7), 8, 10, 12,
            c(8,11), 13, 14, 12, 12, 13, 14, 0)

Pre <- list(0, 1, 1, 1, 3, 3, 3, c(4,7), 2, 5,
            7, c(6,10,11), c(8,12), c(9,13))


durCC<-vector(mode='numeric',length=Ns)
g<-make_graph(elos)
plot(g,vertex.color='white')
sp<-all_simple_paths(g,from=1,to=14)
l<-length(sp)

plot(g, vertex.color='white')
# Inspecione visualmente se as arestas batem com a figura
print(paste("Número de caminhos de 1 a 14:", l))

#2-cria amostras das duracoes dos caminhos
dur<-matrix(rep(0,Ns*n),nrow = Ns,ncol=n)
for(j in 1:Ns){
  for(i in 2:(n-1)){
    dur[j,i]<-ceiling(rtriangle(1,parDur[i,1],parDur[i,3],parDur[i,2]))
  }
}

# 3-para cada cenário calcule duracao CC
dc<-vector(mode="numeric",length=l)
for (i in 1:Ns){
  d<-dur[i,]
  for(j in 1:l){
    dc[j]<-sum(d[sp[[j]]])
  }
  icc<-which.max(dc)
  durCC[i] <-dc[icc]
}

# 4- Analise preliminar
print(summary(durCC))
hist(durCC)
plot(ecdf(durCC))

summary(durCC)

quantile(durCC, 0.85)

funcCpm <- function(n=9,
                    d=c(0,2,6,4,3,5,4,2,0),
                    Suc=list(c(2,3,4),c(5,7),8,6,8,8,9,9,0),
                    Pre=list(0,1,1,1,2,4,2,c(3,5,6),c(7,8)))
{
  est <- rep(0, n)
  eft <- rep(0, n)
  lst <- rep(0, n)
  lft <- rep(0, n)

  # ---------- FORWARD ----------
  for(i in 1:n){
    if(Pre[[i]][1] != 0){
      est[i] <- max(eft[Pre[[i]]])
    }
    eft[i] <- est[i] + d[i]
  }

  # ---------- BACKWARD ----------
  lft[n] <- eft[n]
  lst[n] <- lft[n] - d[n]

  for(i in (n-1):1){
    if(Suc[[i]][1] != 0){
      lft[i] <- min(lst[Suc[[i]]])
    } else {
      lft[i] <- eft[n]
    }
    lst[i] <- lft[i] - d[i]
  }

  slack <- lst - est

  list(est=est, lst=lst, slack=slack, duracao=eft[n])
}

d <- parDur[,2]
r <- funcCpm(n, d, Suc, Pre)

cronograma <- data.frame(
  atividade = 1:n,
  inicio    = r$est,
  duracao   = parDur[,1]
)
print(cronograma)

cronograma <- data.frame(
  atividade = 1:n,
  inicio    = r$est,
  duracao   = d
)

cronograma$fim <- cronograma$inicio + cronograma$duracao

# caminho crítico (slack = 0)

## Diagrama de Gantt simples (sem destaque do caminho crítico)
ggplot(cronograma,
    aes(xmin = inicio,
     xmax = fim,
     ymin = as.numeric(factor(atividade)) - 0.4,
     ymax = as.numeric(factor(atividade)) + 0.4)) +

  geom_rect(fill = "steelblue", colour = "white", linewidth = 0.4) +

  geom_text(aes(x = (inicio + fim) / 2,
       y = as.numeric(factor(atividade)),
       label = sprintf("d=%.0f", duracao)),
      size = 2.8, colour = "white") +

  # linha do término do projeto
  geom_vline(xintercept = r$duracao, linetype = "dashed", colour = "red", linewidth = 0.8) +

  scale_y_continuous(breaks = seq_len(n), labels = paste0("A", seq_len(n))) +

  labs(title = "Diagrama de Gantt",
    x = "Tempo",
    y = "Atividade") +

  theme_minimal(base_size = 11) +
  theme(panel.grid.minor = element_blank(), panel.grid.major.y = element_blank())

"""## Comparação

"""

suppressMessages(library(igraph))
library(ggplot2)
set.seed(42)

# ============================================================
# ESTRUTURAS DE DADOS
# ============================================================
n  <- 14
Ns <- 10000

parDur <- matrix(data = c(
  0,   0.1, 0.2,
  4,   6,   10,
  2,   5,   8,
  2,   3,   6,
  0.5, 1,   2,
  3,   6,   10,
  1,   2,   4,
  0.5, 1,   3,
  2,   3,   6,
  2,   3,   5,
  1,   2,   3,
  1,   2,   4,
  3,   5,   8,
  0,   0.1, 0.2
), ncol = 3, byrow = TRUE)
# colunas: [Min, Mprov (moda), Max]

elos <- c(1,2, 1,3, 1,4, 2,9, 3,5, 3,6, 3,7,
          4,8, 5,10, 6,12, 7,11, 7,8, 8,13,
          9,14, 10,12, 11,12, 12,13, 13,14)

Suc <- list(c(2,3,4), 9, c(5,6,7), 8, 10, 12,
            c(8,11), 13, 14, 12, 12, 13, 14, 0)

Pre <- list(0, 1, 1, 1, 3, 3, 3, c(4,7), 2, 5,
            7, c(6,10,11), c(8,12), c(9,13))

rtri <- function(n, a, c, b) {
  # a=min, b=max, c=modo
  if (b == a) return(rep(a, n))
  u  <- runif(n)
  fc <- (c - a) / (b - a)
  ifelse(u < fc,
    a + sqrt(u  * (b - a) * (c - a)),
    b - sqrt((1 - u) * (b - a) * (b - c))
  )
}

g  <- make_graph(elos)
sp <- all_simple_paths(g, from = 1, to = 14)
l  <- length(sp)
cat(sprintf("Caminhos encontrados: %d\n", l))
for (k in seq_len(l))
  cat(sprintf("  Caminho %d: %s\n", k,
              paste(as.integer(sp[[k]]), collapse = " -> ")))

funcCpm <- function(n, d, Suc, Pre) {
  est <- eft <- lst <- lft <- numeric(n)

  # Forward pass
  cpmf <- function(s, est) {
    eft[s] <<- est[s] + d[s]
    if (Suc[[s]][1] != 0)
      for (i in Suc[[s]]) {
        if (est[i] < eft[s]) est[i] <- eft[s]
        est <- cpmf(i, est)
      }
    est
  }

  # Backward pass
  cpmb <- function(s, lft) {
    lst[s] <<- lft[s] - d[s]
    if (Pre[[s]][1] != 0)
      for (i in Pre[[s]]) {
        if (lft[i] > lst[s]) lft[i] <- lst[s]
        lft <- cpmb(i, lft)
      }
    lft
  }

  rf  <- cpmf(1, est)
  lf  <- rep(rf[n] + d[n], n)
  rb  <- cpmb(n, lf) - d
  list(est = rf, lst = rb, slack = rb - rf)
}

dur <- matrix(0, nrow = Ns, ncol = n)
for (i in 2:(n - 1))                       # ativ 1 e 14 = duracao 0
  dur[, i] <- ceiling(rtri(Ns,
                            parDur[i, 1],
                            parDur[i, 2],
                            parDur[i, 3]))

path_dur <- matrix(0, nrow = Ns, ncol = l)
for (j in seq_len(l))
  path_dur[, j] <- rowSums(dur[, as.integer(sp[[j]]), drop = FALSE])

# Duração total do projeto e índice do caminho crítico
durCC  <- apply(path_dur, 1, max)
icc    <- apply(path_dur, 1, which.max)   # caminho crítico de cada cenário

# ITEM 1 – Duração total do projeto
cat(sprintf("  Média   : %.2f\n",  mean(durCC)))
cat(sprintf("  Mediana : %.2f\n",  median(durCC)))
cat(sprintf("  Desvio  : %.2f\n",  sd(durCC)))
cat(sprintf("  Min/Max : %d / %d\n", min(durCC), max(durCC)))
cat(sprintf("  P85     : %.1f\n",  quantile(durCC, 0.85)))

# =========================
# HISTOGRAMA
# =========================

hist(
  durCC,
  breaks = 30,
  col = "steelblue",
  border = "white",
  main = "Distribuição Empírica da Duração Total do Projeto",
  xlab = "Duração (u.t.)",
  ylab = "Frequência"
)

# Linha do percentil 85
abline(
  v = quantile(durCC, 0.85),
  col = "orange",
  lwd = 2,
  lty = 2
)

legend(
  "topright",
  legend = sprintf("P85 = %.1f", quantile(durCC, 0.85)),
  col = "orange",
  lwd = 2,
  lty = 2,
  bty = "n"
)

# =========================
# ECDF
# =========================

plot(
  ecdf(durCC),
  main = "ECDF – Duração Total do Projeto",
  xlab = "Duração (u.t.)",
  ylab = "P(T ≤ t)",
  col = "steelblue",
  lwd = 2
)

abline(
  h = 0.85,
  col = "orange",
  lwd = 2,
  lty = 2
)

abline(
  v = quantile(durCC, 0.85),
  col = "orange",
  lwd = 2,
  lty = 2
)

legend(
  "bottomright",
  legend = sprintf("P85 = %.1f", quantile(durCC, 0.85)),
  col = "orange",
  lwd = 2,
  lty = 2,
  bty = "n"
)

cat("\n========== ITEM 2: P(atividade no caminho crítico) ==========\n")

contCC <- rep(0, n)

for (i in seq_len(Ns)) {
  contCC[as.integer(sp[[icc[i]]])] <-
    contCC[as.integer(sp[[icc[i]]])] + 1
}

probCC <- contCC / Ns

for (i in seq_len(n)) {
  cat(sprintf("  Atividade %2d: %.1f%%\n", i, probCC[i] * 100))
}

# =========================
# GRÁFICO DE BARRAS
# =========================

barplot(
  probCC * 100,
  names.arg = paste0("A", 1:n),
  col = ifelse(probCC > 0, "steelblue", "gray85"),
  main = "Probabilidade de Cada Atividade Estar no Caminho Crítico",
  xlab = "Atividade",
  ylab = "Probabilidade (%)",
  ylim = c(0, 110)
)

# ============================================================
# ITEM 4 – Cronograma com 85% de chance de ser cumprido
# ============================================================

cat("\n========== ITEM 4: Cronograma com 85% de chance ==========\n")

# P85 da duração total
prazo85 <- as.numeric(quantile(durCC, 0.85))

# P85 dos inícios e durações
si85 <- apply(
  est_mc,
  2,
  function(x) as.numeric(quantile(x, 0.85))
)

di85 <- apply(
  dur,
  2,
  function(x) as.numeric(quantile(x, 0.85))
)

# Cronograma
cron <- data.frame(
  Atividade = 1:n,
  Inicio = round(si85, 1),
  Duracao = round(di85, 1),
  Fim = round(si85 + di85, 1)
)

cat(sprintf(
  "  Prazo do projeto com 85%% de chance: %.1f u.t.\n\n",
  prazo85
))

print(cron)
